### PR TITLE
Worked and Implemented Issue#40

### PR DESCRIPTION
**Pull request by nub-rin**
I have successfully Implemented #40 

I try to test every possible scenarios I can think, but If i missed any. Kindly ping me so that I can take a look and help fix it.

Any suggestions is much appreciated!!

Happy Hacking!

### CODE REVIEW

**Comment by KorryKatti** [comment]
will check and let you know. Thanks for the PR

**Comment by KorryKatti** [comment]
@nub-rin It works flawlessly , just one small issue 

whenever user enters wrong password it shows wrong password entered but then the room button just become unclickable to make way for a second try. The user is having to restart the client to click again. Fix that and the PR will be merged

**Comment by nub-rin** [comment]
Alright! I'll work on it and send a PR.

**Comment by nub-rin** [comment]
@KorryKatti I have managed to narrow down the issue and fixed it and pushed the fix to the branch, kindly check it out and let me know if you find any more issues.

Happy Hacking!!

**Comment by KorryKatti** [comment]
> @KorryKatti I have managed to narrow down the issue and fixed it and pushed the fix to the branch, kindly check it out and let me know if you find any more issues.
> 
> Happy Hacking!!

will check and let you know

**Comment by KorryKatti** [comment]
it works , thanks for the PR

happy coding

**Pull request merged**
