### PR TITLE
Fix message duplication and improve chat room handling

### PR DESCRIPTION
**Pull request by spline2hg**
# Message Duplication Fix and Chat Improvements

## Problem
Users experienced message duplication when clicking on chat rooms multiple times. This was caused by:
1. Redundant message loading from both local storage and server

## Solution
This PR implements a comprehensive fix for message handling:

### Client Changes
- Prevent unnecessary room reloading
- Use server as single source of truth for messages

### Server Changes
- Add new endpoint `/get_all_messages` for complete history

## Testing Done
- Manually verified no message duplication occurs
- Tested room switching with various message loads
- Verified backward compatibility with existing features

Please review the code thoroughly for any potential issues or improvements, as I'm still learning and appreciate any feedback

### CODE REVIEW

**Comment by KorryKatti** [comment]
will take a look into it and it will approve/disapprove in an hour

**Comment by spline2hg** [comment]
ok yeah ,great

**Comment by KorryKatti** [comment]
checked to be working , merging now 

Thank you for your PR

**Comment by spline2hg** [comment]
yeah cool man

**Pull request merged**
