### PR TITLE
One key AES encryption added

### PR DESCRIPTION
**Pull request by Reterics**
Messages are encrypted and decrypted via secret_key provided by userinfo.json or default key.

**Features:**
- Encryption/Decryption exclusively on the client side.
- Uses salting to protect from Rainbow Table Attacks

**Another future upgrade options**
- End-to-end encryption: Much harder to implement

### CODE REVIEW

**Comment by Reterics** [comment]
If you need to generate your own secret key, you can use the following example:

```python
from client.security import aes_to_base64,  generate_aes_key

print(aes_to_base64(generate_aes_key()))
```


image

**Comment by KorryKatti** [comment]
> If you need to generate your own secret key, you can use the following example:
> 
> ```python
> from client.security import aes_to_base64,  generate_aes_key
> 
> print(aes_to_base64(generate_aes_key()))
> ```
> 
> image

the secret.key needs to be placed on server or client side ? sorry for the dumb question

**Comment by Reterics** [comment]
> > If you need to generate your own secret key, you can use the following example:
> > ```python
> > from client.security import aes_to_base64,  generate_aes_key
> > 
> > print(aes_to_base64(generate_aes_key()))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > image
> 
> the secret.key needs to be placed on server or client side ? sorry for the dumb question

It will be in the client side.

Currently it is working like this:

- Client tries to get the secretkey from **userinfo.json**,
- If it fails or the userinfo doesn't have the key, then it will load the default key from **client/security.py line 7**


So if you don't want to customize it, you can safely remove from userinfo.json, but either way, everything i added is exclusively on client side.

**Comment by KorryKatti** [comment]
> > > If you need to generate your own secret key, you can use the following example:
> > > ```python
> > > from client.security import aes_to_base64,  generate_aes_key
> > > 
> > > print(aes_to_base64(generate_aes_key()))
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > image
> > 
> > 
> > the secret.key needs to be placed on server or client side ? sorry for the dumb question
> 
> It will be in the client side.
> 
> Currently it is working like this:
> 
>     * Client tries to get the secretkey from **userinfo.json**,
> 
>     * If it fails or the userinfo doesn't have the key, then it will load the default key from **client/security.py line 7**
> 
> 
> So if you don't want to customize it, you can safely remove from userinfo.json, but either way, everything i added is exclusively on client side.

alright that works , one last question is that every user having different secret.key would effect the encryption right ?

**Comment by Reterics** [comment]
> > > > If you need to generate your own secret key, you can use the following example:
> > > > ```python
> > > > from client.security import aes_to_base64,  generate_aes_key
> > > > 
> > > > print(aes_to_base64(generate_aes_key()))
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > image
> > > 
> > > 
> > > the secret.key needs to be placed on server or client side ? sorry for the dumb question
> > 
> > 
> > It will be in the client side.
> > Currently it is working like this:
> > ```
> > * Client tries to get the secretkey from **userinfo.json**,
> > 
> > * If it fails or the userinfo doesn't have the key, then it will load the default key from **client/security.py line 7**
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So if you don't want to customize it, you can safely remove from userinfo.json, but either way, everything i added is exclusively on client side.
> 
> alright that works , one last question is that every user having different secret.key would effect the encryption right ?

Yes, the user can only read the messages that were encrypted with the same key that is currently used.

If a group needs to communicate each other, then all member need to have the same secret key.

Also if you need anything else to make this PR easier to be integrated to the app, let me know, and i update it.

**Comment by KorryKatti** [comment]
> > > > > If you need to generate your own secret key, you can use the following example:
> > > > > ```python
> > > > > from client.security import aes_to_base64,  generate_aes_key
> > > > > 
> > > > > print(aes_to_base64(generate_aes_key()))
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > image
> > > > 
> > > > 
> > > > the secret.key needs to be placed on server or client side ? sorry for the dumb question
> > > 
> > > 
> > > It will be in the client side.
> > > Currently it is working like this:
> > > ```
> > > * Client tries to get the secretkey from **userinfo.json**,
> > > 
> > > * If it fails or the userinfo doesn't have the key, then it will load the default key from **client/security.py line 7**
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > So if you don't want to customize it, you can safely remove from userinfo.json, but either way, everything i added is exclusively on client side.
> > 
> > 
> > alright that works , one last question is that every user having different secret.key would effect the encryption right ?
> 
> Yes, the user can only read the messages that were encrypted with the same key that is currently used.
> 
> If a group needs to communicate each other, then all member need to have the same secret key.
> 
> Also if you need anything else to make this PR easier to be integrated to the app, let me know, and i update it.


Sure i will make a separate issue for it. Thanks for the PR, will merge as soon as i test it

**Comment by KorryKatti** [comment]
@Reterics 'MAC check failed`

steps to reproduce:
1. run server at one place and copy paste client and change userinfo ( usernames of all three and secret key of only one )
2. error pops up 
3. change it back to correct secret key
4. cant send messages anymore , no one is able to 
5. also unable to create new room on reopening client if one user on server has altered and then restored to original secret key

possible fixes : display error with bad security key to the person at fault when joining the room and let other users keep chatting

it works great when the same copy is ran without any changes ( only  username change )

**Comment by Reterics** [comment]
It is not the best solution, but i made the following:

If the client fails to decrypt one or more message, it sends the information to the server, and the server stores it in an error list.

When we request the message list, we will receive the error list as well, so we will know if someone could not decrypt our message.


Képernyőkép 2024-10-12 192758

**Comment by KorryKatti** [comment]
> It is not the best solution, but i made the following:
> 
> If the client fails to decrypt one or more message, it sends the information to the server, and the server stores it in an error list.
> 
> When we request the message list, we will receive the error list as well, so we will know if someone could not decrypt our message.
> 
> image

looks good , will test and merge if no issues

**Comment by KorryKatti** [comment]
@Reterics when the server is stopped in between and restarted , the cient is unable to send messages , and also on restarting client, rooms are not visible and not being able to create new ones too

everything is working fine before server restart tho

**Comment by Reterics** [comment]
I added a reconnection config to the socketio.Client along with error handling. and restarted both client and server several times, it seems to be working.

**SocketIO config**: 
 `
sio = socketio.Client(reconnection=True, reconnection_attempts=5, reconnection_delay=2)
`

For this I needed to move user_list and message_list polling into the **on_connect** function.

**Client side logs:**

image

Can you make a try with this update?

**Comment by KorryKatti** [comment]
> I added a reconnection config to the socketio.Client along with error handling. and restarted both client and server several times, it seems to be working.
> 
> **SocketIO config**: 
>  `
> sio = socketio.Client(reconnection=True, reconnection_attempts=5, reconnection_delay=2)
> `
> 
> For this I needed to move user_list and message_list polling into the **on_connect** function.
> 
> **Client side logs:**
> 
> image
> 
> Can you make a try with this update?
> 

Will check and report , might take time as I don't have my laptop today

**Comment by Reterics** [comment]
> > I added a reconnection config to the socketio.Client along with error handling. and restarted both client and server several times, it seems to be working.
> > **SocketIO config**:
> > `sio = socketio.Client(reconnection=True, reconnection_attempts=5, reconnection_delay=2)`
> > For this I needed to move user_list and message_list polling into the **on_connect** function.
> > **Client side logs:**
> > image
> > Can you make a try with this update?
> 
> Will check and report , might take time as I don't have my laptop today

It's okay, let me know if you need anything else.

**Comment by KorryKatti** [comment]
> > > I added a reconnection config to the socketio.Client along with error handling. and restarted both client and server several times, it seems to be working.
> > > **SocketIO config**:
> > > `sio = socketio.Client(reconnection=True, reconnection_attempts=5, reconnection_delay=2)`
> > > For this I needed to move user_list and message_list polling into the **on_connect** function.
> > > **Client side logs:**
> > > image
> > > Can you make a try with this update?
> > 
> > 
> > Will check and report , might take time as I don't have my laptop today
> 
> It's okay, let me know if you need anything else.

ok i tested it and its unable to create rooms , could you look into it

**Comment by KorryKatti** [comment]
@Reterics the rooms are being added to the json file but the client isn't showing them

**Comment by KorryKatti** [comment]
> > @Reterics the rooms are being added to the json file but the client isn't showing them
> 
> I added 2 new rooms while i kept open the client. First one empty, second one is assigned a user. The updating and communication is working on start and restart.
> 
> image
> 
> Since the room handling functionality is not changed in this PR, I verified this with origin/main branch, and it works the same. image
> 
> The current behavior is expected or it has the bug by default and we need to show all of the rooms regardless of the current user being in any of them?

shows all rooms right now , select rooms and search implemented in future

**Comment by Reterics** [comment]
I uploaded the changes, you should se all the rooms

**Comment by KorryKatti** [comment]
> I uploaded the changes, you should see all the rooms

will check and let you know

**Comment by KorryKatti** [comment]
works perfect now, thanks for the PR. Also do look out for future issues if you would like to contribute more.


Happy coding and thanks for answering my questions and taking out the time to fix the code continously

**Comment by Reterics** [comment]
> works perfect now, thanks for the PR. Also do look out for future issues if you would like to contribute more.
> 
> Happy coding and thanks for answering my questions and taking out the time to fix the code continously

Thank you, anytime! I'm glad it works, and I may check other issues as well in the future.

Happy coding for you too

**Pull request merged**
